Repository UniPatas/UniPatas, pull requests merged in 2023-11, with the labels that each got.

#15 LP03-157 | Costruir componente navBar da tela home
  package-lock.json
  package.json
  src/app/adote/layout.jsx
  src/app/adote/page.jsx
  src/app/ajuda/layout.jsx
  src/app/ajuda/page.jsx
  src/app/doe/layout.jsx
  src/app/doe/page.jsx
  src/app/globals.css
  src/app/layout.js
  src/app/layout.jsx
  src/app/login/layout.jsx
  src/app/login/page.jsx
  src/app/ongs/layout.jsx
  src/app/ongs/page.jsx
  src/app/page.jsx
  src/app/sobre-nos/layout.jsx
  src/app/sobre-nos/page.jsx
  src/components/Home/Login/Login.jsx
  src/components/Home/NavBar.jsx
Labels: Front-End

#18 LP03-157 | NavBar - *[CORREÇÃO DE ROTAS]*
  src/app/adote/layout.jsx
  src/app/adote/page.jsx
  src/app/ajuda/layout.jsx
  src/app/doe/layout.jsx
  src/app/layout.jsx
  src/app/ongs/layout.jsx
  src/app/page.jsx
  src/app/sobre-nos/layout.jsx
  src/components/Home/SliderOngs/SliderOngs.jsx
  src/components/Layout.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved

#4 LP03-235 | Criar componente de footer da página home
  src/app/home/layout.jsx
  src/app/home/page.jsx
  src/assets/icon-tiktok.png
  src/assets/icons8-twitterx-100.png
  src/components/Home/Footer.jsx
  src/components/Layout.jsx
Labels: Front-End, ct-failed, LG01, awaiting, ct-06-aproved, ct-09-aproved, ct-08-aproved

#17 LP02 131- Codificar a tela de cadastro
  src/app/cadastro/layout.jsx
  src/app/cadastro/page.jsx
  src/app/globals.css
  src/app/login/layout.jsx
  src/components/Home/Cadastro/Cadastro.jsx
  src/components/Home/Login/Login.jsx
Labels: Front-End

#13 LP03-264 | Criar container doe pagina de feed adote
  src/app/adote/layout.jsx
  src/assets/exemplo.png
  src/components/ContainerImg.jsx
Labels: Front-End, ct-01-aproved

#20 LP03 265 + LP2 267 | Criar componente visual do botão de criar novas publicações (Tela de feed adote) e Criar modal de criação de nova publicação (Feed adote)
  src/app/adote/layout.jsx
  src/assets/cat-adote.png
  src/assets/dog-adote.png
  src/assets/plus-button.png
  src/assets/sexo-feminino.png
  src/assets/sexo-masculino.png
  src/components/Adote/BarraHomeAdote.jsx
  src/components/Adote/BotaoCriarPubli/BotaoCriarPubli.jsx
  src/components/Adote/BotaoCriarPubli/ModalPubli.jsx
  src/components/Adote/BotaoCriarPubli/UploadImg.jsx
  src/components/Adote/ContainerImg.jsx
  tailwind.config.js
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved, ct-04-aproved, LG01, ct-06-aproved

#21 LP03 158 | Criar componente de destaque adoção
  src/app/page.jsx
  src/components/Home/DestaqueAdocao.jsx
Labels: Front-End, ct-failed, awaiting

#27 Criei o componente NavigateToHome
  src/app/doe/layout.jsx
  src/components/Doe/NavigateToHome.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved

#23 LP03-250 | Componente de destaque de notícias (Forum)
  Back-end/Adote/.idea/workspace.xml
  Back-end/Adote/src/Main.java
  src/app/page.jsx
  src/components/Home/ComponenteForum.jsx
Labels: Front-End, ct-03-aproved, ct-failed, awaiting

#30 LP03-160 | Construir componente do chatBot
  src/app/chatBot/layour.jsx
  src/app/chatBot/page.jsx
  src/app/globals.css
  src/app/home/layout.jsx
  src/app/layout.jsx
  src/assets/cachorroHeaderChatBot.png
  src/components/Home/ChatBot/ChatBot.jsx
  src/components/Home/ChatBot/Modal.jsx
  src/components/Home/ChatBot/Styles/iconStyle.css
  src/components/Layout.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved

#22 LP03 249 | Componente de anuncio (Container de anúncio do patrocinador) - home page
  Back-end/Adote/.idea/workspace.xml
  src/app/page.jsx
  src/components/Home/ContainerAnuncio.jsx
Labels: Front-End, ct-02-aproved, ct-03-aproved, ct-failed, awaiting
