Repository UniPatas/UniPatas, pull requests merged in 2023-12, with the labels that each got.

#28 Criei container de imagem para página DOE
  src/app/doe/layout.jsx
  src/assets/banner_donation.png
  src/components/Doe/ContainerImgDoe.jsx
Labels: Front-End, awaiting, fix

#51 LP03-361 | Codificar tela de cadastro ONG
  src/app/cadastro-concluido/layout.jsx
  src/app/cadastro-concluido/page.jsx
  src/app/cadastro-ongs/layout.jsx
  src/app/cadastro-ongs/page.jsx
  src/app/globals.css
  src/app/layout.jsx
  src/app/redes-sociais/layout.jsx
  src/app/redes-sociais/page.jsx
  src/assets/imagemSideBarCadastro.png
  src/components/Home/Cadastro/Cadastro.jsx
  src/components/Home/Cadastro/CadastroOngs/CadastroConcluido.jsx
  src/components/Home/Cadastro/CadastroOngs/CadastroOngs.jsx
  src/components/Home/Cadastro/CadastroOngs/MultiFormStep.jsx
  src/components/Home/Cadastro/CadastroOngs/RedeSociais.jsx
  src/components/Home/Login/Login.jsx
  src/components/Home/Login/testar.jpeg
  src/contexts/CadastroContext.jsx
Labels: Front-End

#55 LP03-266 | Criar componente visual do container de filtros e busca (Pagina de feed adote)
  src/app/adote/layout.jsx
  src/app/globals.css
  src/components/Adote/BotaoCriarPubli/ModalPubli.jsx
  src/components/Adote/SearchFilter.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved, ct-04-aproved, ct-05-aproved

#56 LP03 351 Container de exibição dos cards de QR Code das ongs (DOE)
  src/app/doe/layout.jsx
  src/assets/Tag.png
  src/assets/Tag1.png
  src/assets/Unipatinhas.jpeg
  src/assets/cantinho.png
  src/assets/filozinho.png
  src/assets/qrcode.png
  src/assets/qrcodeyellow.png
  src/components/Doe/ConteinerQrcode/Cards.jsx
Labels: Front-End

#65 LP03-352 Container com fundo de animal que induza a compartilhar (DOE)
  src/app/doe/layout.jsx
  src/assets/compartilhe.jpeg
  src/components/Doe/ConteinerCompartilhe/BannerCompartilhe.jsx
Labels: Front-End, ct-01-aproved, ct-failed

#66 LP02-402 Inserir efeito hover e focus para acessibilidade na tela login e cadastro.
  src/components/Home/Cadastro/Cadastro.jsx
  src/components/Home/Login/Login.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved, ct-03-aproved

#68 LP02-403 Aplicar o link no nome UniPatas da tela login e cadastro
  src/components/Home/Cadastro/Cadastro.jsx
  src/components/Home/Login/Login.jsx
Labels: Front-End, ct-01-aproved, ct-02-aproved

#75 LP03-406 Ajustes na tela doe
  src/components/Doe/ConteinerCompartilhe/BannerCompartilhe.jsx
  src/components/Doe/ConteinerQrcode/Cards.jsx
Labels: ct-01-aproved, ct-02-aproved

#81 LP03-386 | Conectar o chatBot front com o back do chat bot
  BackEnd/BotCaramelo/__pycache__/Chatbot.cpython-36.pyc
  BackEnd/BotCaramelo/cursoreact.code-workspace
  db.sqlite3
  db.sqlite3-shm
  db.sqlite3-wal
  src/app/favicon.ico
  src/app/globals.css
  src/components/Home/ChatBot/ChatBot.jsx
  src/components/Home/ChatBot/Modal.jsx
  src/components/Home/ChatBot/Styles/iconStyle.css
  src/components/Home/ChatBot/ToolTips/ToolTip.jsx
Labels: Front-End

#79 LP03 358 | Criar componente de dúvidas frequentes (Home)
  src/app/page.jsx
  src/assets/arrow.png
  src/components/Home/DuvidasFrequentes/DuvidasFrequentes.jsx
  src/components/Home/DuvidasFrequentes/ShowMore.jsx
Labels: Front-End

#82 LP03-409 Textos adicionados na tela doe
  src/components/Doe/Parceiros/ConteinerPaceiros.jsx
Labels: Front-End, ct-01-aproved

#88 LP03-248 | Atualizando informações dos cards das ongs
  src/components/Home/Sliders/SliderOngs.jsx
Labels: Front-End

#87 LP03-410 Ajuste no cadastro ong.
  src/components/Home/Cadastro/CadastroOngs/CadastroOngs.jsx
Labels: Front-End, ct-01-aproved

#91 LP03 157 | Atualizações na NavBar
  src/app/layout.jsx
  src/components/Home/ChatBot/ChatBot.jsx
  src/components/Home/DuvidasFrequentes/DuvidasFrequentes.jsx
  src/components/Home/NavBar.jsx
  src/components/Home/Sliders/SliderOurHist.jsx
Labels: Front-End

#92 LP03-158 | Destaque adoção
  src/assets/doguineo.jpg
  src/assets/gatinhas.jpg
  src/assets/pingo.jpg
  src/components/Home/ContainerAnuncio.jsx
  src/components/Home/DestaqueAdocao.jsx
  src/components/Home/DuvidasFrequentes/DuvidasFrequentes.jsx
  src/components/Home/Footer.jsx
  src/components/Home/Sliders/SliderNoticia.jsx
  src/components/Home/Sliders/SliderOngs.jsx
Labels: Front-End
